# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac5a4e0ec469f09c3df120c2c4877c48341a38b6a7837b0f4e54525c3ab59a2d5720d40e0802e84466e11fa20b8540b3587a2cf40d444a9cd15705b9c74f4908

test:
  secret_key_base: f3353b3098c5ac177041212e634f815723f2d12e242f2397779e1ba098b08fd8fb972d372218a8f45a9833a0fe1572bf6b7f4a5419b65567450e9fd8da705607

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
